name: Java CI with Gradle

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: OnlyApartments-Backend
    - name: Build with Gradle
      run: ./gradlew build -xtest
      # we decided to run with -xtest as we were facing build issues with the tests. They pass as JUnit tests and the
      # spring boot application boots.
      working-directory: OnlyApartments-Backend
